name: release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]"

  workflow_dispatch:

jobs:
  upload-nupkg:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: setup dotnet 7.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"

      - name: install workload
        shell: pwsh
        run: |
          dotnet workload install maui
          dotnet workload install android
          dotnet workload install ios

      - name: download native assets
        shell: pwsh
        run: scripts/download-assets.ps1

      - name: pack
        shell: pwsh
        run: dotnet pack -c Release

      - name: push
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        shell: pwsh
        run: ./scripts/push.ps1 "$env:NUGET_API_KEY"
